[package]
name = "macfarquhar"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
actix-cors = "0.6.5"
serde_json = "1.0.114"
serde = { version="1.0.197", features = ["derive"]}
actix-service = "2.0.2"
futures = "0.3.30"
